const capabilities = [
  { title: "AI workflows", description: "Turn product ideas into shipped features with prompts, iteration, and approval loops." },
  { title: "Code intelligence", description: "Generate, review, and refactor code from a single conversation thread." },
  { title: "Team sync", description: "Keep design, engineering, and product aligned around the same source of truth." },
];
const metrics = [
  { value: "3.4x", label: "faster prototyping" },
  { value: "92%", label: "workflow adoption" },
  { value: "24/7", label: "agent coverage" },
];
export default function Home() {
  return (
    <div className="min-h-screen bg-[#050816] text-slate-100">
      <div className="absolute inset-0 -z-10 overflow-hidden"><div className="absolute left-1/2 top-[-10rem] h-[32rem] w-[32rem] -translate-x-1/2 rounded-full bg-[radial-gradient(circle,_rgba(96,165,250,0.35),_rgba(15,23,42,0)_68%)] blur-3xl" /><div className="absolute inset-0 bg-[linear-gradient(to_bottom,_rgba(15,23,42,0.2),_rgba(5,8,22,0.98))]" /></div>
      <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6 lg:px-8">
        <div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-sky-400/40 bg-sky-500/10 text-sm font-bold text-sky-300">C</div><span className="text-lg font-semibold tracking-tight">codex</span></div>
        <nav className="hidden items-center gap-8 text-sm text-slate-300 md:flex"><a href="#features" className="transition hover:text-white">Features</a><a href="#workflow" className="transition hover:text-white">Workflow</a><a href="#pricing" className="transition hover:text-white">Pricing</a><a href="#docs" className="transition hover:text-white">Docs</a></nav>
        <div className="flex items-center gap-3"><button className="hidden rounded-full border border-white/10 px-4 py-2 text-sm text-slate-200 transition hover:border-sky-400/50 hover:text-white sm:inline-flex">Sign in</button><button className="rounded-full bg-sky-400 px-4 py-2 text-sm font-medium text-slate-950 transition hover:bg-sky-300">Start free</button></div>
      </header>
      <main className="mx-auto max-w-6xl px-6 pb-20 pt-8 lg:px-8">
        <section className="grid items-center gap-12 pb-12 pt-8 lg:grid-cols-[1.1fr_0.9fr] lg:pt-12"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-sky-400/30 bg-sky-500/10 px-3 py-1 text-xs font-medium text-sky-200"><span className="h-2 w-2 rounded-full bg-sky-300" />New: autonomous product sprints</div><h1 className="max-w-xl text-5xl font-semibold tracking-[-0.06em] text-white sm:text-6xl">Build the next big thing with <span className="text-sky-300">codex</span>.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">The AI workspace for shipping product ideas, writing code, and coordinating every decision from concept to launch.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><button className="rounded-full bg-white px-6 py-3 text-sm font-medium text-slate-950 transition hover:bg-slate-200">Start building</button><button className="rounded-full border border-white/10 bg-white/3 px-6 py-3 text-sm font-medium text-white transition hover:border-sky-400/40 hover:bg-sky-500/5">Book a demo</button></div><div className="mt-10 grid max-w-lg gap-4 sm:grid-cols-3">{metrics.map((metric) => <div key={metric.label} className="rounded-2xl border border-white/10 bg-white/3 p-4 backdrop-blur-sm"><div className="text-2xl font-semibold text-white">{metric.value}</div><div className="mt-1 text-xs uppercase tracking-[0.18em] text-slate-400">{metric.label}</div></div>)}</div></div>
          <div className="relative"><div className="absolute inset-0 rounded-[2rem] bg-[radial-gradient(circle_at_top,_rgba(56,189,248,0.38),_rgba(15,23,42,0)_62%)] blur-2xl"/><div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-slate-950/80 shadow-[0_0_80px_rgba(56,189,248,0.15)] backdrop-blur-xl"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div className="flex items-center gap-2"><span className="h-3 w-3 rounded-full bg-rose-400"/><span className="h-3 w-3 rounded-full bg-amber-400"/><span className="h-3 w-3 rounded-full bg-emerald-400"/></div><span className="rounded-full border border-sky-500/30 bg-sky-500/10 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.22em] text-sky-200">live sprint</span></div><div className="space-y-5 p-5"><div className="rounded-2xl border border-emerald-400/20 bg-emerald-500/5 p-4"><div className="mb-2 flex items-center justify-between text-xs uppercase tracking-[0.2em] text-emerald-300"><span>status</span><span>healthy</span></div><div className="text-sm text-slate-200">Feature rollout is on track and deployment previews are updating in real time.</div></div><div className="rounded-2xl border border-white/10 bg-slate-900/80 p-4 font-mono text-sm text-slate-200"><div className="flex items-center gap-2 text-slate-500"><span>~/agents</span><span className="ml-auto">● running</span></div><div className="mt-4 space-y-2 text-slate-300"><div><span className="text-sky-300">$</span> prompt: “Ship a mobile-first onboarding flow”</div><div><span className="text-sky-300">$</span> generate components + analytics hooks</div><div><span className="text-emerald-300">✓</span> QA review passed</div><div><span className="text-sky-300">$</span> publish to preview environment</div></div></div></div></div></div>
        </section>
        <section id="features" className="py-16"><div className="mb-10 max-w-2xl"><p className="text-sm font-medium uppercase tracking-[0.24em] text-sky-300">The platform</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.05em] text-white sm:text-4xl">One workspace for every stage of product delivery.</h2></div><div className="grid gap-5 md:grid-cols-3">{capabilities.map((feature) => <div key={feature.title} className="rounded-3xl border border-white/10 bg-white/3 p-6 backdrop-blur-sm"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-2xl bg-sky-500/10 text-lg text-sky-300">✦</div><h3 className="text-xl font-semibold text-white">{feature.title}</h3><p className="mt-3 text-base leading-7 text-slate-300">{feature.description}</p></div>)}</div></section>
        <section id="workflow" className="grid gap-8 rounded-[2rem] border border-white/10 bg-white/3 p-6 py-10 backdrop-blur-sm lg:grid-cols-[0.9fr_1.1fr] lg:p-10"><div><p className="text-sm font-medium uppercase tracking-[0.24em] text-sky-300">Workflow</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.05em] text-white">From prompt to production in a single loop.</h2><p className="mt-4 text-base leading-7 text-slate-300">Codex combines a product brain, code generation, and deployment visibility so your team can move from idea to insight without context switching.</p></div><div className="grid gap-4 sm:grid-cols-2">{["Discover product opportunities","Generate implementation plans","Review code with guardrails","Ship to preview and production"].map((step,index)=><div key={step} className="rounded-2xl border border-white/10 bg-slate-950/70 p-4"><div className="mb-3 flex h-8 w-8 items-center justify-center rounded-full bg-sky-500/10 text-sm font-medium text-sky-200">0{index+1}</div><p className="text-base text-slate-200">{step}</p></div>)}</div></section>
        <section id="pricing" className="py-16"><div className="rounded-[2rem] border border-sky-400/20 bg-[linear-gradient(135deg,_rgba(14,165,233,0.18),_rgba(15,23,42,0.85))] p-8 sm:p-10"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-medium uppercase tracking-[0.24em] text-sky-200">Launch faster</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.05em] text-white sm:text-4xl">Turn ideas into momentum.</h2></div><button className="rounded-full bg-sky-400 px-6 py-3 text-sm font-semibold text-slate-950 transition hover:bg-sky-300">Try codex free</button></div></div></section>
      </main>
    </div>
  );
}
